// <auto-generated />
using EShopGames.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShopGames.ProductAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EShopGames.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpg",
                            Name = "Name1212",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name2",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name3",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name4",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name5",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name6",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name7",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name8",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name9",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name10",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "Beatiful Picture",
                            Description = "Decription",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Uncharted_3_Boxart.jpg/270px-Uncharted_3_Boxart.jpgTYyQDkQbjuP8qKLK9kBdS9+QM90z996vrwBnoNOVjzzUUVrgaNiu6cI0Hn9yh1KgjLSefL4qlFKSAz4fBWooqA//9k=",
                            Name = "Name11",
                            Price = 99.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
